# Generated by Django 4.2.6 on 2023-11-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('text1', models.CharField(max_length=200)),
                ('image', models.ImageField(default='uploads/sliders/profile.png', upload_to='uploads/sliders')),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.ImageField(default='uploads/images/profile.png', upload_to='uploads/images'),
        ),
    ]
